language: python
python:
  - "2.7"
  - "3.5"
env:
  - TEST_DIR=test
script:
  - python -m doctest lib/sinon/util/CollectionHandler.py
  - cd $TEST_DIR
  - python -m unittest TestSinonBase TestSinonSpy TestSinonStub TestSinonSandbox
