language: python
python:
  - "2.7"
  - "3.5"
env:
  - MAIN_DIR=sinon
script:
  - cd $MAIN_DIR
  - python -m doctest test/ActualUseCases.py
  - python -m doctest lib/sinon/util/CollectionHandler.py
  - cd test
  - python -m unittest TestSinonBase TestSinonSpy TestSinonStub TestSinonSandbox TestSinonMock
